//! Helpers to obtain traces suitable for diagnostics from timely / differential.

/// An error generated by this crate's connect functions.
#[derive(Debug)]
pub enum ConnectError {
    IoError(std::io::Error),
    Other(String),
}

impl From<std::io::Error> for ConnectError {
    fn from(e: std::io::Error) -> Self {
        ConnectError::IoError(e)
    }
}

pub mod receive;
